### ISSUE TITLE
Less dependency?

### ISSUE THREAD

**Issue by hyiltiz** [lacerbi/bads#2]
The package has quite a few dependencies structured into a couple of directories. Would it be possible to skim down all nonessential dependencies, and use a standard directory structure like ./bin, ./lib/share, ./lib/ etc.?

**Comment by lacerbi** [comment]
Are these dependencies causing any issue?
Otherwise, I agree that the organization could be improved (e.g., the ./utils folder is a bit of a mess). I might clean up it a bit in the future, although probably not soon -- unless there are specific reasons. Also, most folders have a specific meaning (e.g., acquisition functions, poll functions, search functions, etc.), and I think it makes sense to keep them that way.

**Comment by hyiltiz** [comment]
Not really causing issues per se, so based on if it aint broke dont fix it, maybe postponing until it needs changing is a good idea 👍
